// Mock data for the Job Portal app

export const mockUsers = [
  {
    id: '1',
    email: 'john.doe@example.com',
    fullName: 'John Doe',
    userType: 'jobseeker',
    phone: '+1234567890',
    location: 'New York, NY',
    bio: 'Experienced software developer with a passion for mobile app development.',
    skills: 'React Native, JavaScript, TypeScript, Node.js, MongoDB',
    experience: '5',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    email: 'jane.smith@techcorp.com',
    fullName: 'Jane Smith',
    userType: 'recruiter',
    phone: '+1234567891',
    location: 'San Francisco, CA',
    bio: 'Senior Technical Recruiter at Tech Corp with 8 years of experience.',
    company: 'Tech Corp',
    createdAt: '2024-01-10T09:00:00Z',
  },
  {
    id: '3',
    email: 'mike.johnson@example.com',
    fullName: 'Mike Johnson',
    userType: 'jobseeker',
    phone: '+1234567892',
    location: 'Austin, TX',
    bio: 'Full-stack developer specializing in React and Node.js applications.',
    skills: 'React, Node.js, Express, PostgreSQL, AWS',
    experience: '3',
    createdAt: '2024-01-12T14:30:00Z',
  },
];

export const mockJobs = [
  {
    id: '1',
    title: 'Senior React Native Developer',
    company: 'Tech Innovations Inc.',
    location: 'New York, NY',
    type: 'full-time',
    remote: true,
    salary: '$120,000 - $150,000',
    experience: 'Senior (5+ years)',
    description: 'We are looking for a Senior React Native Developer to join our mobile development team. You will be responsible for developing high-quality mobile applications for both iOS and Android platforms using React Native framework.',
    requirements: [
      '5+ years of experience in React Native development',
      'Strong knowledge of JavaScript and TypeScript',
      'Experience with Redux or Context API',
      'Familiarity with native iOS and Android development',
      'Knowledge of RESTful APIs and GraphQL',
      'Experience with testing frameworks (Jest, Detox)',
    ],
    benefits: [
      'Competitive salary and equity package',
      'Comprehensive health insurance',
      'Flexible working hours',
      'Remote work options',
      'Professional development budget',
      '25 days paid vacation',
    ],
    postedDate: '2024-01-20T10:00:00Z',
    recruiterId: '2',
    applicationsCount: 12,
    status: 'active',
  },
  {
    id: '2',
    title: 'Frontend Developer',
    company: 'Digital Solutions LLC',
    location: 'San Francisco, CA',
    type: 'full-time',
    remote: false,
    salary: '$90,000 - $120,000',
    experience: 'Mid-level (3-5 years)',
    description: 'Join our frontend team to build amazing user experiences. You will work on modern web applications using React, TypeScript, and other cutting-edge technologies.',
    requirements: [
      '3+ years of experience with React',
      'Proficiency in HTML, CSS, and JavaScript',
      'Experience with TypeScript',
      'Knowledge of modern CSS frameworks (Tailwind, Styled Components)',
      'Understanding of responsive design principles',
      'Experience with version control (Git)',
    ],
    benefits: [
      'Health, dental, and vision insurance',
      '401(k) with company matching',
      'Flexible PTO policy',
      'Learning and development opportunities',
      'Team building events',
    ],
    postedDate: '2024-01-18T14:30:00Z',
    recruiterId: '2',
    applicationsCount: 8,
    status: 'active',
  },
  {
    id: '3',
    title: 'Mobile App Developer',
    company: 'StartupXYZ',
    location: 'Austin, TX',
    type: 'contract',
    remote: true,
    salary: '$80 - $100/hour',
    experience: 'Mid-level (2-4 years)',
    description: 'We need a talented mobile app developer to help us build our next-generation mobile application. This is a contract position with potential for full-time conversion.',
    requirements: [
      '2+ years of mobile app development experience',
      'Experience with React Native or Flutter',
      'Knowledge of mobile app deployment processes',
      'Understanding of mobile UI/UX best practices',
      'Experience with API integration',
    ],
    benefits: [
      'Competitive hourly rate',
      'Flexible schedule',
      'Remote work',
      'Opportunity for full-time conversion',
    ],
    postedDate: '2024-01-17T09:15:00Z',
    recruiterId: '2',
    applicationsCount: 5,
    status: 'active',
  },
  {
    id: '4',
    title: 'Full Stack Developer',
    company: 'WebTech Solutions',
    location: 'Chicago, IL',
    type: 'full-time',
    remote: false,
    salary: '$100,000 - $130,000',
    experience: 'Mid-level (3-5 years)',
    description: 'Looking for a Full Stack Developer to work on both frontend and backend development. You will be involved in the entire development lifecycle from conception to deployment.',
    requirements: [
      'Experience with React and Node.js',
      'Knowledge of databases (PostgreSQL, MongoDB)',
      'Understanding of RESTful API design',
      'Experience with cloud platforms (AWS, Azure)',
      'Familiarity with DevOps practices',
    ],
    benefits: [
      'Comprehensive benefits package',
      'Stock options',
      'Professional development budget',
      'Modern office environment',
      'Catered meals',
    ],
    postedDate: '2024-01-16T11:45:00Z',
    recruiterId: '2',
    applicationsCount: 15,
    status: 'active',
  },
  {
    id: '5',
    title: 'Junior Software Developer',
    company: 'CodeCraft Inc.',
    location: 'Seattle, WA',
    type: 'full-time',
    remote: true,
    salary: '$70,000 - $85,000',
    experience: 'Entry-level (0-2 years)',
    description: 'Great opportunity for a junior developer to grow their career. You will work alongside senior developers and contribute to various projects while learning industry best practices.',
    requirements: [
      'Bachelor\'s degree in Computer Science or related field',
      'Basic knowledge of JavaScript and React',
      'Understanding of HTML and CSS',
      'Familiarity with Git version control',
      'Strong problem-solving skills',
      'Eagerness to learn new technologies',
    ],
    benefits: [
      'Mentorship program',
      'Health insurance',
      'Flexible working hours',
      'Learning and development budget',
      'Company laptop and equipment',
    ],
    postedDate: '2024-01-15T16:20:00Z',
    recruiterId: '2',
    applicationsCount: 25,
    status: 'active',
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    company: 'CloudFirst Technologies',
    location: 'Denver, CO',
    type: 'full-time',
    remote: true,
    salary: '$110,000 - $140,000',
    experience: 'Senior (4+ years)',
    description: 'We are seeking a DevOps Engineer to help us scale our infrastructure and improve our deployment processes. You will work with cutting-edge cloud technologies and automation tools.',
    requirements: [
      '4+ years of DevOps experience',
      'Experience with AWS or Azure',
      'Knowledge of Docker and Kubernetes',
      'Proficiency in Infrastructure as Code (Terraform, CloudFormation)',
      'Experience with CI/CD pipelines',
      'Strong scripting skills (Bash, Python)',
    ],
    benefits: [
      'Competitive salary',
      'Equity participation',
      'Remote-first culture',
      'Top-tier equipment',
      'Unlimited PTO',
      'Conference attendance budget',
    ],
    postedDate: '2024-01-14T13:10:00Z',
    recruiterId: '2',
    applicationsCount: 7,
    status: 'active',
  },
];

export const mockApplications = [
  {
    id: '1',
    jobId: '1',
    job: mockJobs[0],
    applicant: {
      name: 'John Doe',
      email: 'john.doe@example.com',
      phone: '+1234567890',
      location: 'New York, NY',
      skills: 'React Native, JavaScript, TypeScript, Node.js, MongoDB',
    },
    status: 'pending',
    appliedDate: '2024-01-21T10:30:00Z',
    coverLetter: 'I am excited to apply for the Senior React Native Developer position. With over 5 years of experience in mobile app development, I have successfully delivered numerous React Native applications for both iOS and Android platforms. My expertise includes working with Redux for state management, integrating RESTful APIs, and implementing automated testing using Jest and Detox. I am passionate about creating high-quality, user-friendly mobile experiences and would love to contribute to your team.',
    experience: '5',
    expectedSalary: '$130,000',
  },
  {
    id: '2',
    jobId: '2',
    job: mockJobs[1],
    applicant: {
      name: 'Mike Johnson',
      email: 'mike.johnson@example.com',
      phone: '+1234567892',
      location: 'Austin, TX',
      skills: 'React, Node.js, Express, PostgreSQL, AWS',
    },
    status: 'reviewing',
    appliedDate: '2024-01-19T14:15:00Z',
    lastUpdate: '2024-01-20T09:00:00Z',
    coverLetter: 'I am writing to express my interest in the Frontend Developer position at Digital Solutions LLC. As a full-stack developer with 3 years of experience, I have a strong foundation in React and modern frontend technologies. I have worked extensively with TypeScript and have experience building responsive, accessible web applications. I am excited about the opportunity to focus on frontend development and contribute to creating amazing user experiences.',
    experience: '3',
    expectedSalary: '$95,000',
  },
  {
    id: '3',
    jobId: '1',
    job: mockJobs[0],
    applicant: {
      name: 'Sarah Wilson',
      email: 'sarah.wilson@example.com',
      phone: '+1234567893',
      location: 'Los Angeles, CA',
      skills: 'React Native, Swift, Kotlin, Firebase, GraphQL',
    },
    status: 'accepted',
    appliedDate: '2024-01-18T11:45:00Z',
    lastUpdate: '2024-01-22T16:30:00Z',
    coverLetter: 'I am thrilled to apply for the Senior React Native Developer role. With 6 years of experience in mobile development, including 4 years specifically with React Native, I have led the development of several successful mobile applications. My background includes native iOS and Android development, which gives me a deep understanding of platform-specific requirements and optimization techniques. I am passionate about mobile technology and would be excited to bring my expertise to your team.',
    experience: '6',
    expectedSalary: '$140,000',
  },
  {
    id: '4',
    jobId: '3',
    job: mockJobs[2],
    applicant: {
      name: 'Alex Chen',
      email: 'alex.chen@example.com',
      phone: '+1234567894',
      location: 'San Diego, CA',
      skills: 'Flutter, Dart, React Native, Firebase, MongoDB',
    },
    status: 'rejected',
    appliedDate: '2024-01-17T16:20:00Z',
    lastUpdate: '2024-01-19T10:15:00Z',
    coverLetter: 'I am interested in the Mobile App Developer contract position at StartupXYZ. I have 2.5 years of experience in mobile app development, primarily using Flutter but also with some React Native experience. I have successfully deployed several apps to both the App Store and Google Play Store. I am comfortable working remotely and am excited about the possibility of contributing to your next-generation mobile application.',
    experience: '2.5',
    expectedSalary: '$85/hour',
  },
  {
    id: '5',
    jobId: '4',
    job: mockJobs[3],
    applicant: {
      name: 'David Brown',
      email: 'david.brown@example.com',
      phone: '+1234567895',
      location: 'Chicago, IL',
      skills: 'React, Node.js, Express, PostgreSQL, Docker, AWS',
    },
    status: 'pending',
    appliedDate: '2024-01-20T09:30:00Z',
    coverLetter: 'I am excited to apply for the Full Stack Developer position at WebTech Solutions. With 4 years of experience in full-stack development, I have worked on numerous projects involving React frontends and Node.js backends. I have experience with PostgreSQL databases and have deployed applications on AWS. I am comfortable working in an office environment and am looking forward to collaborating with your team on exciting projects.',
    experience: '4',
    expectedSalary: '$115,000',
  },
  {
    id: '6',
    jobId: '5',
    job: mockJobs[4],
    applicant: {
      name: 'Emily Davis',
      email: 'emily.davis@example.com',
      phone: '+1234567896',
      location: 'Portland, OR',
      skills: 'JavaScript, React, HTML, CSS, Git, Python',
    },
    status: 'reviewing',
    appliedDate: '2024-01-19T13:45:00Z',
    lastUpdate: '2024-01-21T11:20:00Z',
    coverLetter: 'I am writing to apply for the Junior Software Developer position at CodeCraft Inc. As a recent Computer Science graduate, I have built a solid foundation in JavaScript and React through my coursework and personal projects. I have completed several web applications using React and have experience with Git version control. I am eager to learn from experienced developers and contribute to your team while growing my skills in a professional environment.',
    experience: '0.5',
    expectedSalary: '$75,000',
  },
];

// Export combined data for easy access
export const mockData = {
  users: mockUsers,
  jobs: mockJobs,
  applications: mockApplications,
};

export default mockData;

